source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SlidingTutorial_Example', :exclusive => true do
  pod "SlidingTutorial", :path => "../"
end

target 'SlidingTutorial_Tests', :exclusive => true do
  pod "SlidingTutorial", :path => "../"

  pod 'FBSnapshotTestCase'
end
