source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SlidingTutorial_Example' do
  pod "SlidingTutorial", :path => "../"
end

target 'SlidingTutorial_Tests' do
  pod "SlidingTutorial", :path => "../"

  pod 'FBSnapshotTestCase'
end
